export const QUERY_KEYS = {
  SSR_ERROR: 'SSR_ERROR',
  RECOMMENDED_PLACES: 'RECOMMENDED_PLACES',
  PLACE_CATEGORIES: 'PLACE_CATEGORIES',
  POPULAR_AREAS: 'POPULAR_AREAS',
  PLACE_DETAIL: 'PLACE_DETAIL',
  RELATED_PLACES: 'RELATED_PLACES',
  ALL_AREAS: 'ALL_AREAS',
  SEARCH_PLACES: 'SEARCH_PLACES',
  MY_PROFILE: 'MY_PROFILE',
  PLACE_REVIEWS: 'PLACE_REVIEWS',
};
